package com.qa.Exceptions;

import com.qa.Excercise.DivideByExc;

public class Maths {
	
	public void multiply(int a, int b) throws MultiplyByFiveExc {
		
	int result;

	
	if (a == 5 || b == 5) {
		throw new MultiplyByFiveExc();
	}
	
	


	public void divide(int c, int d) throws DivideByExc {
		int result;
		
		
		
	}
	
	
	
}
}
